repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7 # adjust to your version

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'eef73e2'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
