version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "8001:5432"
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./config/shared_database.env
      - ./config/airflow_database.env

  jnb:
    image: "jupyter/scipy-notebook:414b5d749704"
    ports:
      - "10000:8888"
    volumes:
      - ./kbase/notebooks/:/home/jovyan/work
    env_file:
      - ./config/shared_database.env
      - ./config/jupyter.env
    entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'

  sql_app:
    build: kbase/sql_app/
    ports:
      - "8087:80"
    depends_on:
      - postgres
    env_file:
      - ./config/shared_database.env

  vue_app:
    build: kbase/vue_app/
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    volumes:
      - ./kbase/vue_app/vue_app/src/:/app/src
      - ./kbase/vue_app/vue_app/public/:/app/public

  airflow:
    image: puckel/docker-airflow:1.10.7
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./config/airflow_container.env
      - ./config/shared_database.env
    volumes:
      - ./config/airflow_requirements.txt:/requirements.txt
      - ./kbase/dags/:/usr/local/airflow/dags
      # - ./plugins:/usr/local/airflow/plugins
    logging:
        options:
            max-size: 10m
            max-file: "3"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

volumes:
  pgdata: